version: '3.8'

services:
  react_app:
    image: hashi5_image
    container_name: hashi5
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./src/.env.local
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
